server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://bunjang-dev.c4t2uq2ojemi.ap-northeast-2.rds.amazonaws.com:3306/bunjangDB?autoReconnect=true # 변경해주세요
    username: admin
    password: 1wgdffj3l3LbKKmYToI5
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전